sudo: required
services:
  - docker

before_install:
  - docker build -t utpalmaity/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true utpalmaity/docker-react npm run test -- --coverage
